[package]
name = "fdb"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
name = "fdb"
path = "main.rs"

[dependencies]
fql.path = "../fql"
miette.workspace = true
